package com.skillroute.skillroute_backend.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.time.LocalDateTime;

@Entity
@Table(name = "interviews")
@Getter
@Setter
public class Interview {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /* Basic interview info */
    @Column(nullable = false)
    private String skill;

    @Column(nullable = false)
    private int difficulty;  // 1-5

    @Column(nullable = false)
    private int questionCount;

    /* Interview status */
    @Column(nullable = false)
    private String status;  // "in_progress" or "completed"

    /* Store questions generated by AI */
    @Column(columnDefinition = "TEXT")
    private String questionsJson;  // Store all questions as JSON string

    /* Results (filled after completion) */
    private Integer totalScore;  // 0-100

    @Column(columnDefinition = "TEXT")
    private String overallFeedback;

    /* Timestamps */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    private LocalDateTime completedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        status = "in_progress";  // Default status
    }
}
